### PR TITLE
timetags, nested bundles, higher-level API and various tweaks 

### PR DESCRIPTION
**Pull request by jamieforth**
This is a fairly big set of patches, sorry. The patches from 2010 are from the darcs days that I submitted at the time. Since they were not included in the git repository I assumed either that they were not suitable for inclusion, or you were no longer maintaining the library. Given the recent activity in the project I wanted to offer these changes for your consideration.

### CODE REVIEW

**Comment by zzkt** [comment]
thanks for sending the patches again. I've not been very active in maintenance, but i'll take a closer look when i get a chance (since there appears to be some conflicts, probably introduced with the fix for 'excess padding' i.e. be1a4f5d4b40c2b6473fbbfa176f0c6d666bbc9d )

I've not really kept up with much of the recent discussion around osc, but iirc when you submitted the darcs patches we had a brief discussion about how to separate the 'core' protocol from the useful extras and/or non-standard extensions to osc. is this still an issue?

**Comment by jamieforth** [comment]
Great. There's nothing non-standard regarding osc here, the timetags and nested bundles conform to the spec I believe and play nicely with other osc implementations (dumpOSC, sendOSC, sc, pd). I recall the discussion though. One issue was probably related to sbcl-specific code (using sb-thread, sb-bsd-sockets, sb-ext etc.) which is a good reason not to include the patches until those parts are adapted to use more implementation-independent libraries.

The extras stuff is contained in the devices directory. This could arguably be a separate library, or at least package to distinguish it from the core osc protocol implementation.

**Comment by zzkt** [comment]
just merged 158bd6860d5047017a4bd28c963341afeb7a62ea which reminded me that i've still not merged these changes. maybe time for some more archeology...

**Comment by jamieforth** [comment]
Haha yes, this is on a TODO list, but never quite makes it to the top.

**Comment by zzkt** [comment]
and thus -> 67118a4a14e9defab5308eccec1f0db253015061 (but also #9 )

**Pull request closed without merging**
